name: 'protostar-toolchain'
description: 'Install Protostar'
author: 'Sam Barnes'
branding:
  icon: play-circle
  color: black

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
        echo "~/.protostar/dist/protostar/" >> $GITHUB_PATH
